# Generated by Django 4.1.5 on 2023-02-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "dishes"},
        ),
    ]
