# Generated by Django 4.1.5 on 2023-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_kitchen", "0002_alter_dish_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="cook",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
